services:
  ###> doctrine/doctrine-bundle ###
  database1:
    image: mysql:8.0
    platform: linux/arm64
    container_name: database1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - database1_data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

  ###> phpmyadmin ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database1
    environment:
      PMA_HOST: database1
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "8080:80"
  ###< phpmyadmin ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database1_data:
  ###< doctrine/doctrine-bundle ###